version: '3.8'

services:

  web:
    build: .
    command: >
      bash -c "alembic upgrade head &&
      uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    volumes:
      - .:/usr/src/app
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/task_tracker
    depends_on:
      - db

  db:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_tracker
